name: rewis3dModel
channels:
  - nvidia/label/cuda-12.4.1
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # --- Build Tools (Required for FlashAttn & Pointops) ---
  - gcc=13.2
  - gxx=13.2
  - cmake
  - make
  - ninja
  - git
  # --- CUDA Compiler (The "missing link" for FlashAttn) ---
  - nvidia::cuda-nvcc
  - nvidia::cuda-cudart
  - nvidia::cuda-libraries-dev 
  - nvidia::cuda-profiler-api
  
  # --- Standard Python Libs (Safe to install via Conda) ---
  - sparsehash
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - wandb
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
